name: Expo EAS CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Tjek kode ud
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installer EAS CLI
        run: npm install -g eas-cli

      - name: Installer afhængigheder
        run: npm install

      - name: Log ind i Expo (EAS)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas whoami || eas login --token $EXPO_TOKEN

      - name: Kør build med EAS
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform android --non-interactive

      # Du kan tilføje dette, hvis du vil have preview links eller deploy OTA updates:
      # - name: Udgiv OTA update (valgfrit)
      #   run: eas update --branch main --non-interactive

