name: Expo Build CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Expo App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Skift til den version du bruger

      - name: Install dependencies
        run: npm install

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Authenticate with Expo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: expo login --username ${{ secrets.EXPO_USERNAME }} --password ${{ secrets.EXPO_PASSWORD }}

      - name: Expo Prebuild (optional)
        run: expo prebuild

      - name: Run Expo Build
        run: expo build:android --non-interactive

      # - name: Run tests (disabled for now)
      #   run: npm test

      # - name: Upload artifacts (optional)
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: build-artifacts
      #     path: dist/
